"""Stock catalogue shared by the local app and public source reader."""

STOCKS = {
    'RAAPLUSDT': {
        'ticker': 'AAPL',
        'company': 'Apple',
        'feed': 'https://www.apple.com/newsroom/rss-feed.rss',
        'hosts': ['www.apple.com', 'apple.com'],
        'article_path': '/newsroom/\\d{4}/\\d{2}/[\\w-]+/?',
        'logo': '/logos/AAPL.png',
    },
    'RNVDAUSDT': {
        'ticker': 'NVDA',
        'company': 'NVIDIA',
        'feed': 'https://nvidianews.nvidia.com/cats/press_release.xml',
        'hosts': ['nvidianews.nvidia.com', 'nvidia.com', 'www.nvidia.com'],
        'article_path': '/news/[\\w-]+/?',
        'logo': '/logos/NVDA.svg',
    },
    'RMSFTUSDT': {
        'ticker': 'MSFT',
        'company': 'Microsoft',
        'feed': 'https://news.microsoft.com/feed/',
        'hosts': ['news.microsoft.com'],
        'article_path': '/(?:source/)?\\d{4}/\\d{2}/\\d{2}/[\\w-]+/?',
        'logo': '/logos/MSFT.png',
    },
    'RAMZNUSDT': {
        'ticker': 'AMZN',
        'company': 'Amazon',
        'feed': 'https://ir.aboutamazon.com/rss/pressrelease.aspx',
        'hosts': ['ir.aboutamazon.com'],
        'article_path': '/news-release/news-release-details/\\d{4}/[\\w-]+/default.aspx',
        'logo': '/logos/AMZN.png',
    },
    'RMETAUSDT': {
        'ticker': 'META',
        'company': 'Meta',
        'feed': 'https://investor.atmeta.com/rss/pressrelease.aspx',
        'hosts': ['investor.atmeta.com'],
        'article_path': '/investor-news/press-release-details/\\d{4}/[\\w-]+/default.aspx',
        'logo': '/logos/META.png',
    },
    'RAMDUSDT': {
        'ticker': 'AMD',
        'company': 'AMD',
        'feed': 'https://ir.amd.com/news-events/press-releases/rss',
        'hosts': ['ir.amd.com'],
        'article_path': '/news-events/press-releases/detail/\\d+/[\\w-]+/?',
        'logo': '/logos/AMD.png',
    },
    'RINTCUSDT': {
        'ticker': 'INTC',
        'company': 'Intel',
        'feed': 'https://www.intc.com/news-events/press-releases/rss',
        'hosts': ['www.intc.com'],
        'article_path': '/news-events/press-releases/detail/\\d+/[\\w-]+/?',
        'logo': '/logos/INTC.png',
    },
    'RAVGOUSDT': {
        'ticker': 'AVGO',
        'company': 'Broadcom',
        'feed': 'https://investors.broadcom.com/rss/news-releases.xml',
        'hosts': ['investors.broadcom.com'],
        'article_path': '/news-releases/news-release-details/[\\w-]+/?',
        'logo': '/logos/AVGO.png',
    },
    'RGOOGLUSDT': {
        'ticker': 'GOOGL',
        'company': 'Alphabet / Google',
        'feed': 'https://abc.xyz/rss/pressrelease.aspx',
        'hosts': ['abc.xyz'],
        'article_path': '/investor/news/news\\-details/\\d{4}/[\\w-]+/default.aspx',
        'logo': '/logos/GOOGL.svg',
    },
    'RNFLXUSDT': {
        'ticker': 'NFLX',
        'company': 'Netflix',
        'feed': 'https://ir.netflix.net/rss/PressRelease.aspx',
        'hosts': ['ir.netflix.net'],
        'article_path': '/investor\\-news\\-and\\-events/financial\\-releases/press\\-release\\-details/\\d{4}/[\\w-]+/default.aspx',
        'logo': '/logos/NFLX.png',
    },
    'RCOINUSDT': {
        'ticker': 'COIN',
        'company': 'Coinbase',
        'feed': 'https://investor.coinbase.com/rss/pressrelease.aspx',
        'hosts': ['investor.coinbase.com'],
        'article_path': '/news/news\\-details/\\d{4}/[\\w-]+/default.aspx',
        'logo': '/logos/COIN.png',
    },
    'RCRMUSDT': {
        'ticker': 'CRM',
        'company': 'Salesforce',
        'feed': 'https://investor.salesforce.com/rss/pressrelease.aspx',
        'hosts': ['investor.salesforce.com'],
        'article_path': '/news/news\\-details/\\d{4}/[\\w-]+/default.aspx',
        'logo': '/logos/CRM.png',
    },
    'RQCOMUSDT': {
        'ticker': 'QCOM',
        'company': 'Qualcomm',
        'feed': 'https://investor.qualcomm.com/rss/pressrelease.aspx',
        'hosts': ['investor.qualcomm.com'],
        'article_path': '/news\\-events/press\\-releases/news\\-details/\\d{4}/[\\w-]+/default.aspx',
        'logo': '/logos/QCOM.png',
    },
    'RPYPLUSDT': {
        'ticker': 'PYPL',
        'company': 'PayPal',
        'feed': 'https://investor.pypl.com/rss/pressrelease.aspx',
        'hosts': ['investor.pypl.com'],
        'article_path': '/news\\-and\\-events/news\\-details/\\d{4}/[\\w-]+/default.aspx',
        'logo': '/logos/PYPL.png',
    },
    'RUBERUSDT': {
        'ticker': 'UBER',
        'company': 'Uber',
        'feed': 'https://investor.uber.com/rss/pressrelease.aspx',
        'hosts': ['investor.uber.com'],
        'article_path': '/news\\-events/news/press\\-release\\-details/\\d{4}/[\\w-]+/default.aspx',
        'logo': '/logos/UBER.svg',
    },
    'RNKEUSDT': {
        'ticker': 'NKE',
        'company': 'Nike',
        'feed': 'https://investors.nike.com/rss/pressrelease.aspx',
        'hosts': ['investors.nike.com'],
        'article_path': '/investors/news\\-events\\-and\\-reports/investor\\-news/investor\\-news\\-details/\\d{4}/[\\w-]+/default.aspx',
        'logo': '/logos/NKE.svg',
    },
    'RKOUSDT': {
        'ticker': 'KO',
        'company': 'Coca-Cola',
        'feed': 'https://investors.coca-colacompany.com/news-events/press-releases/rss',
        'hosts': ['investors.coca-colacompany.com'],
        'article_path': '/news-events/press-releases/detail/\\d+/[\\w-]+/?',
        'logo': '/logos/KO.svg',
    },
    'RVUSDT': {
        'ticker': 'V',
        'company': 'Visa',
        'feed': 'https://investor.visa.com/rss/pressrelease.aspx',
        'hosts': ['investor.visa.com'],
        'article_path': '/news/news\\-details/\\d{4}/[\\w-]+/default.aspx',
        'logo': '/logos/V.svg',
    },
    'RMAUSDT': {
        'ticker': 'MA',
        'company': 'Mastercard',
        'feed': 'https://investor.mastercard.com/rss/pressrelease.aspx',
        'hosts': ['investor.mastercard.com'],
        'article_path': '/investor\\-news/investor\\-news\\-details/\\d{4}/[\\w-]+/default.aspx',
        'logo': '/logos/MA.png',
    },
}

def public_stocks():
    return [{'symbol': symbol, 'ticker': row['ticker'], 'company': row['company'],
             'source_url': row['feed'], 'logo': row['logo']}
            for symbol, row in STOCKS.items()]
